### ISSUE TITLE
Endianness and unsafe code

### ISSUE THREAD

**Issue by DemiMarie** [reem/rust-http2parse#1]
The unsafe code in `payload::Setting::to_bytes` and `payload::Setting::from_bytes` seems to assume a certain endianness.

**Comment by riking** [comment]
Pointer alignment issues are also present: https://asan.saethlin.dev/ub?crate=http2parse&version=0.2.2

```
test frame::test::bench_frame_header_parse ... thread 'frame::test::bench_frame_header_parse' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/byteorder-0.3.13/src/lib.rs:292:9:
misaligned pointer dereference: address must be a multiple of 0x4 but is 0x564269b5a665
stack backtrace:
   0: rust_begin_unwind
             at /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_nounwind_fmt
             at /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:106:14
   2: core::panicking::panic_misaligned_pointer_dereference
             at /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:203:5
   3: <byteorder::BigEndian as byteorder::ByteOrder>::read_u32
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/byteorder-0.3.13/src/lib.rs:292:9
   4: http2parse::StreamIdentifier::parse
             at ./src/lib.rs:80:13
   5: http2parse::frame::FrameHeader::parse
             at ./src/frame.rs:51:17
   6: http2parse::frame::test::bench_frame_header_parse::{{closure}}
             at ./src/frame.rs:260:31
   7: test::bench::ns_iter_inner
             at /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/bench.rs:117:19
   8: test::bench::Bencher::iter
             at /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/bench.rs:45:13
   9: http2parse::frame::test::bench_frame_header_parse
             at ./src/frame.rs:248:9
  10: http2parse::frame::test::bench_frame_header_parse::{{closure}}
             at ./src/frame.rs:245:57
  11: core::ops::function::FnOnce::call_once
             at /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
  12: test::types::RunnableTest::run::{{closure}}::{{closure}}
             at /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/test/src/types.rs:149:76

```
